# 服务器基础配置
server:
  port: 8080

# Spring 核心配置
spring:
  application:
    name: spring-rag

  datasource:
    url: jdbc:mysql://localhost:3306/spring_rag?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  output:
    ansi:
      enabled: ALWAYS



# 文件存储
file:
  storage:
    base-path: ./storage/files  # 文件存储基础路径
    max-file-size: 52428800 # 50MB
    allowed-file-types: pdf,txt,md,docx,jpg,png # 允许的文件类型
    temp-path: ./storage/temp # 临时文件存储路径